- name: Install Nginx
  package:
    name: nginx
    state: latest
- name: Replace NGINX config
  template:
    src=templates/nginx.conf
    dest=/etc/nginx/nginx.conf
  notify:
    - NGINX reload
- name: Copy index.html
  template:
    src=templates/index.html
    dest=/var/www/html
  notify:
    - NGINX reload